#ifndef _LIBASSERV_ROBOT_H_
#define _LIBASSERV_ROBOT_H_

#define DEFAULT_DELTA_POS_COEFS { 10000, 800, 1 }
#define DEFAULT_ALPHA_POS_COEFS { 2000, 50, 0.5 }
#define DEFAULT_ALPHA_POS_COEFS { 600, 1, 50 }
#define DEFAULT_DELTA_SPEED_COEFS { 600, 1, 50 }


#define DEFAULT_DIST_SPEED_MAX  1.5
#define DEFAULT_DIST_ACC_MAX    0.5
#define DEFAULT_DIST_DEC_MAX    0.5
#define DEFAULT_ROT_SPEED_MAX   0.8
#define DEFAULT_ROT_ACC_MAX     0.5
#define DEFAULT_ROT_DEC_MAX     0.5

#define DEFAULT_EPSILON_DIST    0.01
#define DEFAULT_EPSILON_SPEED   0.001
#define DEFAULT_EPSILON_THETA   0.05
#define DEFAULT_EPSILON_OMEGA   0.001

#define DEFAULT_TIC_BY_METER    24700
#define DEFAULT_SPACING         0.29

#endif // _LIBASSERV_ROBOT_H_
