#ifndef _LIBASSERV_DEFAULT_H_
#define _LIBASSERV_DEFAULT_H_

#ifndef DEFAULT_DELTA_POS_COEFS
#define DEFAULT_DELTA_POS_COEFS { 600, 1, 50 }
#endif
#ifndef DEFAULT_DELTA_SPEED_COEFS
#define DEFAULT_DELTA_SPEED_COEFS { 600, 1, 50 }
#endif
#ifndef DEFAULT_ALPHA_POS_COEFS
#define DEFAULT_ALPHA_POS_COEFS { 600, 1, 50 }
#endif
#ifndef DEFAULT_ALPHA_SPEED_COEFS
#define DEFAULT_ALPHA_SPEED_COEFS { 100, 0, 0 }
#endif

#ifndef DEFAULT_DIST_SPEED_MAX
#define DEFAULT_DIST_SPEED_MAX 1.5
#endif
#ifndef DEFAULT_DIST_ACC_MAX
#define DEFAULT_DIST_ACC_MAX 0.5
#endif
#ifndef DEFAULT_DIST_DEC_MAX
#define DEFAULT_DIST_DEC_MAX 0.5
#endif
#ifndef DEFAULT_ROT_SPEED_MAX
#define DEFAULT_ROT_SPEED_MAX 0.8
#endif
#ifndef DEFAULT_ROT_ACC_MAX
#define DEFAULT_ROT_ACC_MAX 0.5
#endif
#ifndef DEFAULT_ROT_DEC_MAX
#define DEFAULT_ROT_DEC_MAX 0.5
#endif

#ifndef DEFAULT_EPSILON_DIST
#define DEFAULT_EPSILON_DIST 0.01
#endif
#ifndef DEFAULT_EPSILON_SPEED
#define DEFAULT_EPSILON_SPEED 0.001
#endif
#ifndef DEFAULT_EPSILON_THETA
#define DEFAULT_EPSILON_THETA 0.05
#endif
#ifndef DEFAULT_EPSILON_OMEGA
#define DEFAULT_EPSILON_OMEGA 0.001
#endif

#ifndef DEFAULT_TIC_BY_METER
#define DEFAULT_TIC_BY_METER 25000
#endif
#ifndef DEFAULT_SPACING
#define DEFAULT_SPACING 0.3
#endif

#ifndef DEFAULT_LEFT_COEFS
#define DEFAULT_LEFT_COEFS { 1, 0, 0 }
#endif
#ifndef DEFAULT_RIGHT_COEFS
#define DEFAULT_RIGHT_COEFS { 1, 0, 0 }
#endif


#endif // _LIBASSERV_DEFAULT_H_
